# Processing Traffic Data for Machine Learning Models
## Erica Keklak | 2025-06-25

In [39]:
# Import necessary libraries and packages

import pandas as pd
import geopandas as gpd
import csv

## Highway Traffic Volume

In [42]:
# Read highway traffic volume files from 2014 to 2021, inclusive

path = 'C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/'
pre_2022_station_paths = ['2014_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2014.txt',
                          '2015_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2015.txt',
                          '2016_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2016.txt',
                          '2017_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2017.txt',
                          '2018_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2018.txt',
                          '2019_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2019.txt',
                          '2020_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2020.txt',
                          '2021_station_data/Station_Data_Extract_Pipe_Delimited_CleanData_2021.txt'
                         ]

pre_2022_station_paths = [str(path + year) for year in pre_2022_station_paths]
# for i in range(0, len(pre_2022_station_paths)):
#     pre_2022_station_paths[i] = str(path + pre_2022_station_paths[i])

mod_path = 'C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/'

mod_station_paths = [str(str(year) + '_station_data.csv') for year in range(2014, 2025)]

# Convert them from pipe-delimited text files to CSVs

for year in range(2014, 2022):
    with open(pre_2022_station_paths[year - 2014], 'rt') as file_old:
        reader_pipe = csv.reader(file_old, delimiter = '|')
        with open(mod_station_paths[year - 2014], 'wt') as file_new:
            writer_comma = csv.writer(file_new, delimiter = ',')
            for row in reader_pipe:
                writer_comma.writerow(row)

In [48]:
# Read highway traffic volume files from 2022 to 2023, inclusive

state_abbreviations = ['AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MO', 'MN',
                       'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT',
                       'WA', 'WI', 'WV', 'WY']

path_begin_2022 = 'C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/2022_station_data_txt/'
path_end_2022 = '_2022 (TMAS).STA.txt'
station_paths_2022 = []
for i in range(0, len(state_abbreviations)):
    station_paths_2022 = station_paths_2022 + [str(path_begin_2022 + state_abbreviations[0] + path_end_2022)]
# station_paths_2022 = [str(path_begin_2022 + state_abbreviations[state.index] + path_end_2022) for state in state_abbreviations]

mod_station_paths_2022 = [str(str(state) + '_2022_station_data.csv') for state in state_abbreviations]

path_begin_2023 = 'C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/2023_station_data_txt/'
path_end_2023 = '_2023 (TMAS).STA.txt'
station_paths_2023 = []
for i in range(0, len(state_abbreviations)):
    station_paths_2023 = station_paths_2023 + [str(path_begin_2023 + state_abbreviations[0] + path_end_2023)]
# station_paths_2023 = [str(path_begin_2023 + state_abbreviations[state] + path_end_2023) for state in state_abbreviations]

mod_station_paths_2023 = [str(str(state) + '_2023_station_data.csv') for state in state_abbreviations]

# Convert these from pipe-delimited text files to CSVs also

for state in range(0, len(state_abbreviations)):
    this_state = state_abbreviations[state]
    with open(station_paths_2022[state], 'rt') as file_old:
        reader_pipe = csv.reader(file_old, delimiter = '|')
        with open(mod_station_paths_2022[state], 'wt') as file_new:
            writer_comma = csv.writer(file_new, delimiter = ',')
            for row in reader_pipe:
                writer_comma.writerow(row)

for state in range(0, len(state_abbreviations)):
    this_state = state_abbreviations[state]
    with open(station_paths_2023[state], 'rt') as file_old:
        reader_pipe = csv.reader(file_old, delimiter = '|')
        with open(mod_station_paths_2023[state], 'wt') as file_new:
            writer_comma = csv.writer(file_new, delimiter = ',')
            for row in reader_pipe:
                writer_comma.writerow(row)

In [50]:
# Add them as DataFrames, bypassing reading them just as CSVs

# add , dtype = {} just in case at the end
highway_traffic_2014 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2014_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2015 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2015_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2016 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2016_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2017 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2017_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2018 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2018_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2019 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2019_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2020 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2020_station_data.csv', dtype = {26: object, 27: object, 30: str}))
highway_traffic_2021 = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/2021_station_data.csv', dtype = {26: object, 27: object, 30: str}))

highway_traffic_2022_AL = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/AL_2022_station_data.csv'))
highway_traffic_2022_AR = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/AR_2022_station_data.csv'))
highway_traffic_2022_AZ = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/AZ_2022_station_data.csv'))
highway_traffic_2022_CA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/CA_2022_station_data.csv'))
highway_traffic_2022_CO = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/CO_2022_station_data.csv'))
highway_traffic_2022_CT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/CT_2022_station_data.csv'))
highway_traffic_2022_DE = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/DE_2022_station_data.csv'))
highway_traffic_2022_FL = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/FL_2022_station_data.csv'))
highway_traffic_2022_GA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/GA_2022_station_data.csv'))
highway_traffic_2022_IA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/IA_2022_station_data.csv'))
highway_traffic_2022_ID = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/ID_2022_station_data.csv'))
highway_traffic_2022_IL = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/IL_2022_station_data.csv'))
highway_traffic_2022_IN = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/IN_2022_station_data.csv'))
highway_traffic_2022_KS = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/KS_2022_station_data.csv'))
highway_traffic_2022_KY = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/KY_2022_station_data.csv'))
highway_traffic_2022_LA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/LA_2022_station_data.csv'))
highway_traffic_2022_MA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MA_2022_station_data.csv'))
highway_traffic_2022_MD = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MD_2022_station_data.csv'))
highway_traffic_2022_ME = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/ME_2022_station_data.csv'))
highway_traffic_2022_MI = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MI_2022_station_data.csv'))
highway_traffic_2022_MN = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MN_2022_station_data.csv'))
highway_traffic_2022_MO = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MO_2022_station_data.csv'))
highway_traffic_2022_MS = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MS_2022_station_data.csv'))
highway_traffic_2022_MT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MT_2022_station_data.csv'))
highway_traffic_2022_NC = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NC_2022_station_data.csv'))
highway_traffic_2022_ND = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/ND_2022_station_data.csv'))
highway_traffic_2022_NE = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NE_2022_station_data.csv'))
highway_traffic_2022_NH = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NH_2022_station_data.csv'))
highway_traffic_2022_NJ = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NJ_2022_station_data.csv'))
highway_traffic_2022_NM = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NM_2022_station_data.csv'))
highway_traffic_2022_NV = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NV_2022_station_data.csv'))
highway_traffic_2022_NY = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NY_2022_station_data.csv'))
highway_traffic_2022_OH = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/OH_2022_station_data.csv'))
highway_traffic_2022_OK = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/OK_2022_station_data.csv'))
highway_traffic_2022_OR = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/OR_2022_station_data.csv'))
highway_traffic_2022_PA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/PA_2022_station_data.csv'))
highway_traffic_2022_RI = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/RI_2022_station_data.csv'))
highway_traffic_2022_SC = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/SC_2022_station_data.csv'))
highway_traffic_2022_SD = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/SD_2022_station_data.csv'))
highway_traffic_2022_TN = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/TN_2022_station_data.csv'))
highway_traffic_2022_TX = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/TX_2022_station_data.csv'))
highway_traffic_2022_UT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/UT_2022_station_data.csv'))
highway_traffic_2022_VA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/VA_2022_station_data.csv'))
highway_traffic_2022_VT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/VT_2022_station_data.csv'))
highway_traffic_2022_WA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WA_2022_station_data.csv'))
highway_traffic_2022_WI = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WI_2022_station_data.csv'))
highway_traffic_2022_WV = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WV_2022_station_data.csv'))
highway_traffic_2022_WY = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WY_2022_station_data.csv'))

highway_traffic_2023_AL = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/AL_2023_station_data.csv'))
highway_traffic_2023_AR = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/AR_2023_station_data.csv'))
highway_traffic_2023_AZ = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/AZ_2023_station_data.csv'))
highway_traffic_2023_CA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/CA_2023_station_data.csv'))
highway_traffic_2023_CO = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/CO_2023_station_data.csv'))
highway_traffic_2023_CT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/CT_2023_station_data.csv'))
highway_traffic_2023_DE = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/DE_2023_station_data.csv'))
highway_traffic_2023_FL = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/FL_2023_station_data.csv'))
highway_traffic_2023_GA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/GA_2023_station_data.csv'))
highway_traffic_2023_IA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/IA_2023_station_data.csv'))
highway_traffic_2023_ID = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/ID_2023_station_data.csv'))
highway_traffic_2023_IL = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/IL_2023_station_data.csv'))
highway_traffic_2023_IN = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/IN_2023_station_data.csv'))
highway_traffic_2023_KS = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/KS_2023_station_data.csv'))
highway_traffic_2023_KY = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/KY_2023_station_data.csv'))
highway_traffic_2023_LA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/LA_2023_station_data.csv'))
highway_traffic_2023_MA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MA_2023_station_data.csv'))
highway_traffic_2023_MD = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MD_2023_station_data.csv'))
highway_traffic_2023_ME = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/ME_2023_station_data.csv'))
highway_traffic_2023_MI = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MI_2023_station_data.csv'))
highway_traffic_2023_MN = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MN_2023_station_data.csv'))
highway_traffic_2023_MO = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MO_2023_station_data.csv'))
highway_traffic_2023_MS = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MS_2023_station_data.csv'))
highway_traffic_2023_MT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/MT_2023_station_data.csv'))
highway_traffic_2023_NC = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NC_2023_station_data.csv'))
highway_traffic_2023_ND = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/ND_2023_station_data.csv'))
highway_traffic_2023_NE = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NE_2023_station_data.csv'))
highway_traffic_2023_NH = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NH_2023_station_data.csv'))
highway_traffic_2023_NJ = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NJ_2023_station_data.csv'))
highway_traffic_2023_NM = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NM_2023_station_data.csv'))
highway_traffic_2023_NV = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NV_2023_station_data.csv'))
highway_traffic_2023_NY = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/NY_2023_station_data.csv'))
highway_traffic_2023_OH = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/OH_2023_station_data.csv'))
highway_traffic_2023_OK = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/OK_2023_station_data.csv'))
highway_traffic_2023_OR = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/OR_2023_station_data.csv'))
highway_traffic_2023_PA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/PA_2023_station_data.csv'))
highway_traffic_2023_RI = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/RI_2023_station_data.csv'))
highway_traffic_2023_SC = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/SC_2023_station_data.csv'))
highway_traffic_2023_SD = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/SD_2023_station_data.csv'))
highway_traffic_2023_TN = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/TN_2023_station_data.csv'))
highway_traffic_2023_TX = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/TX_2023_station_data.csv'))
highway_traffic_2023_UT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/UT_2023_station_data.csv'))
highway_traffic_2023_VA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/VA_2023_station_data.csv'))
highway_traffic_2023_VT = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/VT_2023_station_data.csv'))
highway_traffic_2023_WA = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WA_2023_station_data.csv'))
highway_traffic_2023_WI = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WI_2023_station_data.csv'))
highway_traffic_2023_WV = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WV_2023_station_data.csv'))
highway_traffic_2023_WY = pd.DataFrame(pd.read_csv('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Highway Traffic/WY_2023_station_data.csv'))

In [54]:
# Explore columns

highway_traffic_list = [highway_traffic_2014, highway_traffic_2015, highway_traffic_2016, highway_traffic_2017, highway_traffic_2018,
                        highway_traffic_2019, highway_traffic_2020, highway_traffic_2021, highway_traffic_2022_AL, highway_traffic_2022_AR,
                        highway_traffic_2022_AZ, highway_traffic_2022_CA, highway_traffic_2022_CO, highway_traffic_2022_CT, highway_traffic_2022_DE,
                        highway_traffic_2022_FL, highway_traffic_2022_GA, highway_traffic_2022_IA, highway_traffic_2022_ID, highway_traffic_2022_IL,
                        highway_traffic_2022_IN, highway_traffic_2022_KS, highway_traffic_2022_KY, highway_traffic_2022_LA, highway_traffic_2022_MA,
                        highway_traffic_2022_MD, highway_traffic_2022_ME, highway_traffic_2022_MI, highway_traffic_2022_MN, highway_traffic_2022_MO,
                        highway_traffic_2022_MS, highway_traffic_2022_MT, highway_traffic_2022_NC, highway_traffic_2022_ND, highway_traffic_2022_NE,
                        highway_traffic_2022_NH, highway_traffic_2022_NJ, highway_traffic_2022_NM, highway_traffic_2022_NV, highway_traffic_2022_NY,
                        highway_traffic_2022_OH, highway_traffic_2022_OK, highway_traffic_2022_OR, highway_traffic_2022_PA, highway_traffic_2022_RI,
                        highway_traffic_2022_SC, highway_traffic_2022_SD, highway_traffic_2022_TN, highway_traffic_2022_TX, highway_traffic_2022_UT,
                        highway_traffic_2022_VA, highway_traffic_2022_VT, highway_traffic_2022_WA, highway_traffic_2022_WI, highway_traffic_2022_WV,
                        highway_traffic_2022_WY, highway_traffic_2023_AL, highway_traffic_2023_AR, highway_traffic_2023_AZ, highway_traffic_2023_CA,
                        highway_traffic_2023_CO, highway_traffic_2023_CT, highway_traffic_2023_DE, highway_traffic_2023_FL, highway_traffic_2023_GA,
                        highway_traffic_2023_IA, highway_traffic_2023_ID, highway_traffic_2023_IL, highway_traffic_2023_IN, highway_traffic_2023_KS,
                        highway_traffic_2023_KY, highway_traffic_2023_LA, highway_traffic_2023_MA, highway_traffic_2023_MD, highway_traffic_2023_ME,
                        highway_traffic_2023_MI, highway_traffic_2023_MN, highway_traffic_2023_MO, highway_traffic_2023_MS, highway_traffic_2023_MT,
                        highway_traffic_2023_NC, highway_traffic_2023_ND, highway_traffic_2023_NE, highway_traffic_2023_NH, highway_traffic_2023_NJ,
                        highway_traffic_2023_NM, highway_traffic_2023_NV, highway_traffic_2023_NY, highway_traffic_2023_OH, highway_traffic_2023_OK,
                        highway_traffic_2023_OR, highway_traffic_2023_PA, highway_traffic_2023_RI, highway_traffic_2023_SC, highway_traffic_2023_SD,
                        highway_traffic_2023_TN, highway_traffic_2023_TX, highway_traffic_2023_UT, highway_traffic_2023_VA, highway_traffic_2023_VT,
                        highway_traffic_2023_WA, highway_traffic_2023_WI, highway_traffic_2023_WV, highway_traffic_2023_WY]

highway_traffic_dict = {'2014': highway_traffic_2014, '2015': highway_traffic_2015, '2016': highway_traffic_2016, '2017': highway_traffic_2017,
                        '2018': highway_traffic_2018, '2019': highway_traffic_2019, '2020': highway_traffic_2020, '2021': highway_traffic_2021,
                        '2022_AL': highway_traffic_2022_AL, '2022_AR': highway_traffic_2022_AR, '2022_AZ': highway_traffic_2022_AZ,
                        '2022_CA': highway_traffic_2022_CA, '2022_CO': highway_traffic_2022_CO, '2022_CT': highway_traffic_2022_CT,
                        '2022_DE': highway_traffic_2022_DE, '2022_FL': highway_traffic_2022_FL, '2022_GA': highway_traffic_2022_GA,
                        '2022_IA': highway_traffic_2022_IA, '2022_ID': highway_traffic_2022_ID, '2022_IL': highway_traffic_2022_IL,
                        '2022_IN': highway_traffic_2022_IN, '2022_KS': highway_traffic_2022_KS, '2022_KY': highway_traffic_2022_KY,
                        '2022_LA': highway_traffic_2022_LA, '2022_MA': highway_traffic_2022_MA, '2022_MD': highway_traffic_2022_MD,
                        '2022_ME': highway_traffic_2022_ME, '2022_MI': highway_traffic_2022_MI, '2022_MI': highway_traffic_2022_MN,
                        '2022_MO': highway_traffic_2022_MO, '2022_MS': highway_traffic_2022_MS, '2022_MT': highway_traffic_2022_MT,
                        '2022_NC': highway_traffic_2022_NC, '2022_ND': highway_traffic_2022_ND, '2022_NE': highway_traffic_2022_NE,
                        '2022_NH': highway_traffic_2022_NH, '2022_NJ': highway_traffic_2022_NJ, '2022_NM': highway_traffic_2022_NM,
                        '2022_NV': highway_traffic_2022_NV, '2022_NY': highway_traffic_2022_NY, '2022_OH': highway_traffic_2022_OH,
                        '2022_OK': highway_traffic_2022_OK, '2022_OR': highway_traffic_2022_OR, '2022_PA': highway_traffic_2022_PA,
                        '2022_RI': highway_traffic_2022_RI, '2022_SC': highway_traffic_2022_SC, '2022_SD': highway_traffic_2022_SD,
                        '2022_TN': highway_traffic_2022_TN, '2022_TX': highway_traffic_2022_TX, '2022_UT': highway_traffic_2022_UT,
                        '2022_VA': highway_traffic_2022_VA, '2022_VT': highway_traffic_2022_VT, '2022_WA': highway_traffic_2022_WA,
                        '2022_WI': highway_traffic_2022_WI, '2022_WV': highway_traffic_2022_WV,
                        highway_traffic_2022_WY, highway_traffic_2023_AL, highway_traffic_2023_AR, highway_traffic_2023_AZ, highway_traffic_2023_CA,
                        highway_traffic_2023_CO, highway_traffic_2023_CT, highway_traffic_2023_DE, highway_traffic_2023_FL, highway_traffic_2023_GA,
                        highway_traffic_2023_IA, highway_traffic_2023_ID, highway_traffic_2023_IL, highway_traffic_2023_IN, highway_traffic_2023_KS,
                        highway_traffic_2023_KY, highway_traffic_2023_LA, highway_traffic_2023_MA, highway_traffic_2023_MD, highway_traffic_2023_ME,
                        highway_traffic_2023_MI, highway_traffic_2023_MN, highway_traffic_2023_MO, highway_traffic_2023_MS, highway_traffic_2023_MT,
                        highway_traffic_2023_NC, highway_traffic_2023_ND, highway_traffic_2023_NE, highway_traffic_2023_NH, highway_traffic_2023_NJ,
                        highway_traffic_2023_NM, highway_traffic_2023_NV, highway_traffic_2023_NY, highway_traffic_2023_OH, highway_traffic_2023_OK,
                        highway_traffic_2023_OR, highway_traffic_2023_PA, highway_traffic_2023_RI, highway_traffic_2023_SC, highway_traffic_2023_SD,
                        highway_traffic_2023_TN, highway_traffic_2023_TX, highway_traffic_2023_UT, highway_traffic_2023_VA, highway_traffic_2023_VT,
                        highway_traffic_2023_WA, highway_traffic_2023_WI, highway_traffic_2023_WV, highway_traffic_2023_WY}

# for i in range(0, len(highway_traffic_list)):
#     print(str(highway_traffic_list[i]),':\n',highway_traffic_list[i].columns)
highway_traffic_2014.columns

Index(['Record_Type', 'State_Code', 'Station_Id', 'Travel_Dir', 'Travel_Lane',
       'Year_Record', 'F_System', 'Num_Lanes', 'Sample_Type_Volume',
       'Num_Lanes_Volume', 'Method_Volume', 'Sample_Type_Class',
       'Num_Lanes_Class', 'Method_Class', 'Algorithm_Volume', 'Num_Classes',
       'Sample_Type_Truck', 'Num_Lanes_Truck', 'Method_Truck', 'Calibration',
       'Data_Retrieval', 'Type_Sensor_1', 'Type_Sensor_2', 'Primary_Purpose',
       'LRS_Id', 'LRS_Point', 'Latitude', 'Longitude', 'SHRP_Id',
       'Prev_Station_Id', 'Year_Established', 'Year_Discontinued',
       'County_Code', 'Is_Sample', 'Sample_Id', 'NHS', 'Posted_Route_Signing',
       'Posted_Signed_Route', 'Con_Route_Signing', 'Con_Signed_Route',
       'Station_Location'],
      dtype='object')

In [56]:
highway_traffic_2014.head()

,Record_Type,State_Code,Station_Id,Travel_Dir,Travel_Lane,Year_Record,F_System,Num_Lanes,Sample_Type_Volume,Num_Lanes_Volume,...,Year_Discontinued,County_Code,Is_Sample,Sample_Id,NHS,Posted_Route_Signing,Posted_Signed_Route,Con_Route_Signing,Con_Signed_Route,Station_Location
0,S,1,000002,3,2,14,3R,2,T,2,...,,71,Y,000002114563,Y,2,00000072,3,00000002,2.0 Miles East of Madison Co. Line ...
1,S,1,000012,7,2,14,3R,2,T,2,...,,33,N,,Y,2,00000072,3,00000002,2.0 Miles West of AL 247 ...
2,S,1,000017,5,1,14,4R,1,T,1,...,,117,Y,000025119662,Y,3,00000025,0,,2.0 Miles North of I-65 ...
3,S,1,000023,3,1,14,3R,1,T,1,...,,97,N,,Y,2,00000098,3,00000042,1.2 Miles East of Mississippi State Line ...
4,S,1,000024,3,1,14,4R,1,T,1,...,,3,N,,Y,2,00000090,3,00000016,3.0 Miles West of AL 59 ...

In [60]:
# Remove unnecessary columns

for i in range(0, 9):
    dataset = highway_traffic_list[0]
    dataset = dataset.drop(columns = ['Record_Type', 'Station_Id', 'Travel_Dir', 'Travel_Lane', 'Year_Record', 'F_System', 'Sample_Type_Volume',
                                      'Year_Discontinued', 'Sample_Id', 'NHS', 'Posted_Route_Signing', 'Con_Route_Signing', 'Con_Signed_Route',
                                      'Station_Location'], axis = 1) # Year_Discontinued was the first on the right side
highway_traffic_2014.head()

KeyError: "['Record_Type', 'Station_Id', 'Travel_Dir', 'Travel_Lane', 'Year_Record', 'F_System', 'Sample_Type_Volume', 'Year_Discontinued', 'Sample_Id', 'NHS', 'Posted_Route_Signing', 'Con_Route_Signing', 'Con_Signed_Route', 'Station_Location'] not found in axis"

In [ ]:
# Determine the county and state of data points

In [ ]:
# Determine whether or not observations are taken during the day or night

In [ ]:
# Determine the season when the observation was taken

In [ ]:
# Aggregate volumes by year, county, state, time of day, and season

## Highway Rest Stops

In [176]:
# Read highway rest stop volume files

smaller_rest_stop_list_b = gpd.read_file('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Rest Area Map.kml',
                                       driver = 'KML', layer = 'Both'
                                      )
smaller_rest_stop_list_n = gpd.read_file('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Rest Area Map.kml',
                                       driver = 'KML', layer = 'Northbound'
                                      )
smaller_rest_stop_list_s = gpd.read_file('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Rest Area Map.kml',
                                       driver = 'KML', layer = 'Southbound'
                                      )
smaller_rest_stop_list_e = gpd.read_file('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Rest Area Map.kml',
                                       driver = 'KML', layer = 'Eastbound'
                                      )
smaller_rest_stop_list_w = gpd.read_file('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/Rest Area Map.kml',
                                       driver = 'KML', layer = 'Westbound'
                                      )
smaller_rest_stop_list = pd.concat([smaller_rest_stop_list_b, smaller_rest_stop_list_n, smaller_rest_stop_list_s, smaller_rest_stop_list_e,
                                   smaller_rest_stop_list_w])
larger_rest_stop_list = gpd.read_file('C:/Users/EK111/Documents/NJIT/Spotted Lanternfly Project URI Summer 2025/Raw Data Backups/Traffic/US Rest Stops.kml',
                                       driver = 'KML'
                                      )

In [98]:
smaller_rest_stop_list.head()

,Name,description,timestamp,begin,end,altitudeMode,tessellate,extrude,visibility,drawOrder,icon,Exit_Mile,Direction,City_or_Town,Latitude,Longitude,Website,geometry
0,Rest Area,Exit/Mile: Exit 99<br>Direction: Both<br>City ...,NaT,NaT,NaT,None,-1,0,-1,NaN,None,Exit 99,Both,Canyonville,42.942,-123.2926,interstaterestareas.com,POINT Z (-123.29 42.942 0)
1,Rest Area,Exit/Mile: Exit 786<br>Direction: Both<br>City...,NaT,NaT,NaT,None,-1,0,-1,NaN,None,Exit 786,Both,Yreka,41.8547,-122.5727,interstaterestareas.com,POINT Z (-122.57 41.855 0)
2,Welcome Center,Exit/Mile: Exit 667<br>Direction: Both<br>City...,NaT,NaT,NaT,None,-1,0,-1,NaN,None,Exit 667,Both,Anderson,40.4325,-122.2858,interstaterestareas.com,POINT Z (-122.29 40.432 0)
3,Rest Area,Exit/Mile: Exit 51<br>Direction: Both<br>City ...,NaT,NaT,NaT,None,-1,0,-1,NaN,None,Exit 51,Both,Pine Valley,32.757946,-116.48399,interstaterestareas.com,POINT Z (-116.48 32.758 0)
4,Rest Area,Exit/Mile: Exit 96<br>Direction: Both<br>City ...,NaT,NaT,NaT,None,-1,0,-1,NaN,None,Exit 96,Both,Ponce de Leon,30.712901,-85.930074,interstaterestareas.com,POINT Z (-85.93 30.713 0)

In [122]:
larger_rest_stop_list.head()

,Name,description,timestamp,begin,end,altitudeMode,tessellate,extrude,visibility,drawOrder,...,Phone,Handi__capped_Access,RV_Station,Vending,Pet_Area,Wifi,Longitude,Latitude,URL,geometry
0,Aliso Creek,Source: website<br>State: CA<br>Rte: 5<br>Loc2...,NaT,NaT,NaT,None,-1.0,0.0,-1,NaN,...,Yes,Yes,Yes,Yes,Yes,,-117.43297,33.26577,,POINT Z (-117.43 33.266 0)
1,Aliso Creek,Source: website<br>State: CA<br>Rte: 5<br>Loc2...,NaT,NaT,NaT,None,-1.0,0.0,-1,NaN,...,Yes,Yes,Yes,Yes,Yes,,-117.44089,33.27168,,POINT Z (-117.44 33.272 0)
2,Bogard,Source: website<br>State: CA<br>Rte: 44<br>Loc...,NaT,NaT,NaT,None,-1.0,0.0,-1,NaN,...,Yes,Yes,No,Yes,Yes,,-121.13094,40.62283,,POINT Z (-121.13 40.623 0)
3,Boron,Source: website<br>State: CA<br>Rte: 58<br>Loc...,NaT,NaT,NaT,None,-1.0,0.0,-1,NaN,...,Yes,Yes,No,No,Yes,,-117.71746,35.00697,,POINT Z (-117.72 35.007 0)
4,Boron,Source: website<br>State: CA<br>Rte: 58<br>Loc...,NaT,NaT,NaT,None,-1.0,0.0,-1,NaN,...,Yes,Yes,No,No,Yes,,-117.71746,35.00697,,POINT Z (-117.72 35.007 0)

In [110]:
# Read the columns in the longer one

larger_rest_stop_list.columns

Index(['Name', 'description', 'timestamp', 'begin', 'end', 'altitudeMode',
       'tessellate', 'extrude', 'visibility', 'drawOrder', 'icon', 'Source',
       'State', 'Rte', 'Loc2', 'Loc', 'Dir', 'Closed_From', 'Closed_To',
       'Rest_Room', 'Water', 'Picnic_Tables', 'Phone', 'Handi__capped_Access',
       'RV_Station', 'Vending', 'Pet_Area', 'Wifi', 'Longitude', 'Latitude',
       'URL', 'geometry'],
      dtype='object')

In [168]:
# Remove unnecessary columns

smaller_rest_stop_list_b = smaller_rest_stop_list_b.drop(columns = ['Name', 'description', 'timestamp', 'altitudeMode', 'tessellate', 'extrude',
                                                                    'visibility', 'drawOrder', 'icon', 'Exit_Mile', 'Direction', 'Website', 'begin', 'end'
                                                                   ], axis = 1)
smaller_rest_stop_list_n = smaller_rest_stop_list_n.drop(columns = ['Name', 'description', 'timestamp', 'altitudeMode', 'tessellate', 'extrude',
                                                                    'visibility', 'drawOrder', 'icon', 'Exit_Mile', 'Direction', 'Website', 'begin', 'end'
                                                                   ], axis = 1)
smaller_rest_stop_list_s = smaller_rest_stop_list_s.drop(columns = ['Name', 'description', 'timestamp', 'altitudeMode', 'tessellate', 'extrude',
                                                                    'visibility', 'drawOrder', 'icon', 'Exit_Mile', 'Direction', 'Website', 'begin', 'end'
                                                                   ], axis = 1)
smaller_rest_stop_list_e = smaller_rest_stop_list_e.drop(columns = ['Name', 'description', 'timestamp', 'altitudeMode', 'tessellate', 'extrude',
                                                                    'visibility', 'drawOrder', 'icon', 'Exit_Mile', 'Direction', 'Website', 'begin', 'end'
                                                                   ], axis = 1)
smaller_rest_stop_list_w = smaller_rest_stop_list_w.drop(columns = ['Name', 'description', 'timestamp', 'altitudeMode', 'tessellate', 'extrude',
                                                                    'visibility', 'drawOrder', 'icon', 'Exit_Mile', 'Direction', 'Website', 'begin', 'end'
                                                                   ], axis = 1)
larger_rest_stop_list = larger_rest_stop_list.drop(columns = ['Name', 'description', 'timestamp', 'altitudeMode', 'tessellate', 'extrude', 'visibility',
                                                              'drawOrder', 'icon', 'Source', 'Loc2', 'Dir', 'Rest_Room', 'Water', 'Picnic_Tables', 'Phone',
                                                              'Loc', 'Handi__capped_Access', 'RV_Station', 'Vending', 'Pet_Area', 'Wifi', 'URL', 'begin',
                                                              'end', 'Rte', 'Closed_From', 'Closed_To'
                                                             ], axis = 1)

In [170]:
smaller_rest_stop_list_b.head()

    City_or_Town   Latitude   Longitude                    geometry
0    Canyonville     42.942   -123.2926  POINT Z (-123.29 42.942 0)
1          Yreka    41.8547   -122.5727  POINT Z (-122.57 41.855 0)
2       Anderson    40.4325   -122.2858  POINT Z (-122.29 40.432 0)
3    Pine Valley  32.757946  -116.48399  POINT Z (-116.48 32.758 0)
4  Ponce de Leon  30.712901  -85.930074   POINT Z (-85.93 30.713 0)

In [172]:
larger_rest_stop_list.head()

  State   Longitude  Latitude                    geometry
0    CA  -117.43297  33.26577  POINT Z (-117.43 33.266 0)
1    CA  -117.44089  33.27168  POINT Z (-117.44 33.272 0)
2    CA  -121.13094  40.62283  POINT Z (-121.13 40.623 0)
3    CA  -117.71746  35.00697  POINT Z (-117.72 35.007 0)
4    CA  -117.71746  35.00697  POINT Z (-117.72 35.007 0)

In [164]:
pd.unique(larger_rest_stop_list['Closed_To'])

array(['', '6/1/2010', '1/31/2011', '4/30/2010'], dtype=object)

In [ ]:
#